#!/usr/bin/env php
<?php

/*
 * This file is part of the PivotalConnector package.
 * (c) Fabien Potencier <fabien.potencier@symfony-project.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

chdir(dirname(__FILE__));
require_once(dirname(__FILE__).'/cli/config.php');
include(dirname(__FILE__).'/cli.php');
